baseURL = 'https://anatolelefort.net'
languageCode = 'en-us'
title = "Anatole Lefort"
theme = 'motherfuckingwebsite'
[params]
  author = 'Anatole Lefort'
  dateform = 'Jan 02, 2006'
  #Logo = 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=lXtqvU0AAAAJ&citpid=3'
  #Logo = 'https://pbs.twimg.com/profile_images/1646221313906704404/MKlGYus3_400x400.jpg'
  Logo = '/pictures/logo.jpg'

[deployment]
[[deployment.targets]]
name = 'anatolelefort.net'
URL = "s3://anatolelefort.net?endpoint=https://s3.fr-par.scw.cloud&region=fr-par"
